### PR TITLE
[docs] Document String, Array

### PR DESCRIPTION
**Pull request by elliot-nelson**
### SUMMARY

Take an initial stab at documenting Types.  I've chosen the simplest (String) and a relatively complex one (Array) to put my approach through its paces.

### DETAILS

- For `Types` documentation, my opinion is that we should avoid re-documenting the synchronous config methods.  For example, the `Array` type should not document the `.stringArray` method, but instead describe "how Arrays work" (how they parse, what the default values are, oddities or potential pitfalls when working with Arrays, etc.).

- Where possible, I think we should document through examples rather than paragraphs of text.  For Types I've attempted to include actual working program snippets, because (when we get into the more complex types) it's useful to see actual working error output and/or default value behavior.

- My current take is that a Type doc is: a summary, a list of supported properties above and beyond common type properties (this is re-doc from Sync Config), and then a series of examples that document everything else about a Type, for both flagged option and positional varieties.

- Low-key I am attempting to follow Microsoft's [brand voice](https://docs.microsoft.com/en-us/style-guide/top-10-tips-style-voice) (short, direct, but friendly).  Appreciate any feedback pointing out where I'm not, or if you prefer an alternate voice.

### NEXT STEPS

Things I'm still noodling on:

- Are "flagged options" and "positional arguments" different enough that I should include Examples for each as section headers, instead of just including them both in a list?

- Do we need Examples of the usage of every property supported by a type?

- Now that I'm looking over this PR, I see I'm "shortcutting" running examples in some cases (i.e., I'll make a comment and then just include a `console` snippet, assuming the `js` snippet hasn't changed).  This makes sense if you're reading a textbook but isn't optimized for scanning to what you're looking for and reading it, so even though it's kind of painful, maybe we should force every single example to be a js+console pair.

### CODE REVIEW

**Comment by elliot-nelson** [comment]
@nexdrew just a ping - hoping to merge this to get some initial examples checked in (perfect not being enemy of the good etc etc).  Take a look if you get a chance.

**Comment by nexdrew** [comment]
@elliot-nelson Sorry!

Anything you want to add here is fine by me. I will merge and publish.

Thank you for your many contributions!

**Review by nexdrew — APPROVED** [review]
Looks good, thank you so much!

**Comment by nexdrew** [comment]
This should now be live at sywac.io.

**Pull request merged**
